version: 2

updates:
  - package-ecosystem: gomod
    directory: /solar_assistant_monitor
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    assignees:
      - KrzysztofHajdamowicz
    groups:
      go-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      go-security-minor-and-patch:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    assignees:
      - KrzysztofHajdamowicz
    groups:
      actions-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      actions-security-minor-and-patch:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /solar_assistant_monitor
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Warsaw
    assignees:
      - KrzysztofHajdamowicz
    groups:
      docker-minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      docker-security-minor-and-patch:
        applies-to: security-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
